In [43]:
from sklearn.feature_extraction.text import CountVectorizer

simple_train = ['call you tonight', 'Call me a cab', 'Please call me... PLEASE!']

vectorizer = CountVectorizer()

matrix = vectorizer.fit_transform(simple_train).toarray()
print(matrix)
 


[[0 1 0 0 1 1]
 [1 1 1 0 0 0]
 [0 1 1 2 0 0]]


In [44]:
# import these modules
from nltk.stem import PorterStemmer

# Stemming

ps = PorterStemmer()

sentence = "The children are playing in the garden and they will play again tomorrow."

splitedSentence = sentence.split()

for w in splitedSentence:
	print(w, " : ", ps.stem(w))





The  :  the
children  :  children
are  :  are
playing  :  play
in  :  in
the  :  the
garden  :  garden
and  :  and
they  :  they
will  :  will
play  :  play
again  :  again
tomorrow.  :  tomorrow.


In [45]:
!pip install spacy  


^C
ERROR: Operation cancelled by user


In [ ]:
!pip install spaCy

In [ ]:
!pip install numpy==1.26.4 spacy

!python3 -m spacy download en_core_web_sm

INFO: pip is looking at multiple versions of thinc to determine which version is compatible with other requirements. This could take a while.
  Using cached spacy-3.8.2-cp312-cp312-macosx_10_9_x86_64.whl.metadata (27 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 9.2 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 10.1 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 824.1/824.1 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.1/6.1 MB 10.2 MB/s eta 0:00:00a 0:00:01
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: blis
    Found existing installation: blis 1.0.1
    Uninstalling blis-1.0.1:
      Successfully uninstalled blis-1.0.1
  Attempting uninstall: thinc
    Found existing installation: thinc 8.3.2
    Uninstalling thinc-8.3.2:
      Successfully uninstalled thinc-8.3.2

In [ ]:
import spacy  



# Load the language model  
nlp = spacy.load("en_core_web_sm")  

# Create a document  
sentence = "The children are playing in the garden and they will play again tomorrow."
doc = nlp(sentence)  

# Process the document  
for token in doc:  
    print(token.lemma_)

/opt/anaconda3/lib/python3.12/site-packages/spacy/util.py:910: UserWarning: [W095] Model 'en_core_web_sm' (3.7.1) was trained with spaCy v3.7.2 and may not be 100% compatible with the current version (3.8.2). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)


the
child
be
play
in
the
garden
and
they
will
play
again
tomorrow
.


In [ ]:
import csv  
import spacy  
import pandas as pd  

# Load the English language model  
nlp = spacy.load("en_core_web_sm")  

# Path to the CSV file  
file_path = 'spam.csv'  

# Read the CSV file with proper encoding  
df = pd.read_csv(file_path, encoding='latin1')  


# Function to lemmatize text and remove stop words  
def lemaStopWord(text_series):  
    filtered_words = []  

    
    for text in text_series: 

        doc = nlp(text)  # Process the text with spaCy  

        # Filter out stop words and lemmatize the remaining tokens  
        filtered = [token.lemma_ for token in doc if not token.is_stop and not token.is_punct]

        concatenated_lemmas = ' '.join(filtered)  


        filtered_words.append(concatenated_lemmas)  
    
    return filtered_words  







# Apply the function to the DataFrame text series  
filtered_results = lemaStopWord(df["v2"]) 

X =  filtered_results
# Encode labels
y = df["v1"].map({'ham': 0, 'spam': 1})


print(y)






/opt/anaconda3/lib/python3.12/site-packages/spacy/util.py:910: UserWarning: [W095] Model 'en_core_web_sm' (3.7.1) was trained with spaCy v3.7.2 and may not be 100% compatible with the current version (3.8.2). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)


0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: v1, Length: 5572, dtype: int64


In [111]:
from sklearn.model_selection import train_test_split


# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y)

print(X_test)



['go bath msg   lt;#&gt   min', "sad story Man week b'day Wife did'nt wish Parents forget n kid go work colleague wish", 'Hmmm Thk sure get time hop ard Ya 4 free abt Muz u discuss liao', 'stuff sell i.ll tell', 'lol busy', 'force eat slice hungry tho suck Mark get worried know sick turn pizza lol', 'Jokin lar depend phone father lor', 'good let thank God complete drug lot water beautiful day', 'y lei v lazy get wat dat day Ì send da url not work', 'cozy exhaust night.nobody go school work closed', 'home lar Ì wait 4 lor stuff', 'see', 'drug able eat', 'Rose need water season need change poet need imagination phone need ur sms need ur lovely frndship forever', 'ok april not wait', 'SMS AUCTION win Nokia 7250i win free auction send Nokia 86021 HG Suite342/2Lands Row W1JHL 16 +', 'hear', 'black shirt n blue jean thk c Ì', 'hi babe Chloe r u smash saturday night great weekend u miss sp visionsms.com text stop stop 150p text', 'Heart remembr forget soon Bcoz Heart like like one Remembered 

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer


# CountVectorizer()
vectorizer = TfidfVectorizer()  



X_train_vectorized = vectorizer.fit_transform(X_train).toarray()
X_test_vectorized = vectorizer.transform(X_test).toarray()

 

In [141]:
from sklearn.neural_network import MLPClassifier  

# Initialize and train the MLPClassifier  
clf = MLPClassifier(random_state=1, max_iter=300)  
clf.fit(X_train_vectorized, y_train) 

MLPClassifier(max_iter=300, random_state=1)

In [140]:
from sklearn.metrics import accuracy_score  
from sklearn.metrics import classification_report  

# Make predictions on the test set  
y_pred = clf.predict(X_test_vectorized) 

# Calculate the accuracy  
accuracy = accuracy_score(y_test, y_pred) * 100 


print(f"Model accuracy on test set: {accuracy:.2f}")  

cr = classification_report(y_test, y_pred) 

print (cr)


Model accuracy on test set: 98.21
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1210
           1       0.95      0.91      0.93       183

    accuracy                           0.98      1393
   macro avg       0.97      0.95      0.96      1393
weighted avg       0.98      0.98      0.98      1393

